{% set name = "pymace" %}
{% set version = "0.3.10" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ACEsuit/mace/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 12524c0e8e5e414b8fd848369cfc9d46242f97ee5b1b0520e8484141cb850b39

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pytorch >=1.12
    - e3nn =0.4.4
    - numpy <2.0
    - opt_einsum
    - ase
    - torch-ema
    - prettytable
    - matplotlib-base
    - pandas
    - matscipy
    - configargparse
    - gitpython
    - h5py
    - python-hostlist
    - torchmetrics
    - tqdm
    - cuequivariance-torch
    - pyyaml

test:
  imports:
    - mace
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/ACEsuit/mace
  summary: 'MACE - Fast and accurate machine learning interatomic potentials with higher order equivariant message passing.'
  description: |
    MACE provides fast and accurate machine learning interatomic 
    potentials with higher order equivariant message passing. This 
    repository contains the MACE reference implementation developed 
    by Ilyes Batatia, Gregor Simm, and David Kovacs.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://github.com/ACEsuit/mace
  dev_url: https://github.com/ACEsuit/mace

extra:
  recipe-maintainers:
    - fxcoudert
    - jan-janssen
